// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code! 
// 
// Generated by LF-ET 2.2.1 (230526A), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/asciidoctor/asciidoctor-liquibase/lfet/extractor/createIndex.lfet"
// 11.06.2023 15:36
// 
// Changes to this code resulting from refactorings can be synchronised
// with LF-ET using the function "Scrapbook Import".
// 
// Prolog Decision Table ---->
function createIndex(element, currentFile, processModel, logger, vfs) {
    // Prolog Decision Table <----
    
    // Condition B01/01: definition is based on ... format / yaml / yaml definition
    if (
    currentFile.endsWith('yaml')
    )
    {
        // Rule R01 ---->
        
        // Trace ---->
        logger.info(`createIndex - 20230611.153614 - 1 / 2 - ${currentFile} - ${JSON.stringify(processModel)}`)
        // Trace <----
        
        // Action A01/01: extract ... / yaml / extract table on yaml definition
        // ignore
        
        // Rule R01 <----
    }
    else
    {
        // Rule R02 ---->
        
        // Trace ---->
        logger.info(`createIndex - 20230611.153614 - 2 / 2 - ${currentFile} - ${JSON.stringify(processModel)}`)
        // Trace <----
        
        // Action A02: error
        logger.error(`createIndex - 20230611.153614 - Format for ${currentFile} is not supported.`)
        
        // Rule R02 <----
    }
    
    // Epilog Decision Table ---->
}

module.exports = {
  extract: (element, currentFile, processModel, logger, vfs) => {
    return createIndex(element, currentFile, processModel, logger, vfs)
  }
}
// Epilog Decision Table <----

// End of generated JavaScript source code
// Generated by LF-ET 2.2.1 (230526A), https://www.lohrfink.de/lfet

